### ISSUE TITLE
[FEATURE] Testando criar um ISSUE criando uma nova funcionalodade

### ISSUE THREAD

**Issue by luraianne1** [arthusantiago/KeyAnyWhere#3]
**ATENÇÃO**

Apresente a ideia da sua nova funcionalidade em uma ISSUE antes de submeter o código em uma PR.
A sua ideia será avaliada por mim, buscando adequá-la aos objetivos do projeto, podendo ser aprovada ou não.

Use as dicas abaixo:

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luraianne1** [comment]
Isso é uma teste

**Comment by arthusantiago** [comment]
Como é um teste, pode abrir sua PR de teste
